# Generated by Django 5.1 on 2024-10-01 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='feed.message'),
        ),
    ]
